version: '1'
services:
  web:
    image: pharmville-app
    ports:
      - "5000:5000"
    volumes:
      - ./pharm_app:/pharm_app
    working_dir: /pharm_app
    command: flask --debug run --host 0.0.0.0
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pharmville-db
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
