version: '3.8'
services:
  postgres:
    container_name: postgres-db
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: pharm-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5400:5432
volumes:
  postgres: